version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region region-name)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t sample-nba-project .
      - docker tag sample-nba-project:latest repository-uri:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push repository-uri:latest
