version: '3'
services:

  #PHP Service
  dcindesign:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: dcindesign
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: dcindesign
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - dcindesign-network

  #Nginx Service
  dcindesign_webserver:
    image: nginx:alpine
    container_name: dcindesign_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8061:80"
      - "44361:443"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dcindesign-network
  #Mysql database
  dcindesigndb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: dcindesign
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dcindesign_dbdata:/var/lib/mysql
    networks:
      - dcindesign-network
    ports:
      - 33639:3306
volumes:
  dcindesign_dbdata:

#Networks
networks:
  dcindesign-network:
    driver: bridge
